### PR TITLE
Footnotes refactor

### PR DESCRIPTION
**Pull request by hgodinho**
Hello there!

Here is my suggest to [support footnotes](https://github.com/inokawa/remark-docx/issues/33). Still has limitations in inline footnotes, as mdast is returning a `text` type and not a [`footnote` type](https://github.com/syntax-tree/mdast#footnotes).

I also added a `.editorconfig` to avoid messing up with your code, as my vscode is configured to use `tab_width = 4`.

### CODE REVIEW

**Comment by inokawa** [comment]
@hgodinho 
Could you update snapshot of test for footnotes?
Thank you for your PR!

**Comment by hgodinho** [comment]
never used snapshot before, nice discovery!

**Comment by hgodinho** [comment]
in my machine the problem is in the latex spec, that goes beyond my knowledge =/

**Review by inokawa — APPROVED** [review]
Thanks!

**Comment by Fenugreek** [comment]
In my .md file, I used the syntax for footnotes `[^1]` and `[^1]:` as in the mdast README[^1]. 
Footnotes do not appear in the generated .docx. 
I am using version 0.1.6. 
Is the syntax incorrect? Where can I look this up? Interestingly, that syntax works here for this comment.
Thanks. 

[^1]: https://github.com/syntax-tree/mdast

**Pull request merged**
